name: Run tests

on:
  push:
    branches: '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node.js
      uses: actions/setup-node@v1
    - name: Install packages
      run: npm ci
    - name: Run tests
      run: npm run test
